import type { Metadata } from "next";
import { jost } from "./fonts";
import "./globals.css";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "dark",
          "bg-background:dark",
          "text-foreground",
          jost.className,
          "antialiased"
        )}
      >
        {children}
      </body>
    </html>
  );
}